service: eph-api

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: eu-west-2
  profile: eph-dev

package:
  exclude:
    - env/**
    - node_modules/**

functions:
  api:
    handler: api.handler
    events:
      - http:
          path: /
          method: POST

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    slim: true
