service: eph-api

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-2
  profile: eph-dev

functions:
  vectors:
    handler: handler.vectors
    events:
      - http:
          path: vectors
          method: POST
