service: eph-api

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-2
  profile: eph-dev

package:
  exclude:
    - venv/**
    - node_modules/**

functions:
  api:
    handler: api.handler
    events:
      - http:
          path: /
          method: POST
          cors: true

plugins:
  - serverless-python-requirements
  - serverless-offline
custom:
  pythonRequirements:
    dockerizePip: non-linux
    zip: true
    slim: true
