service: eph-api

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-2
  profile: eph-dev

functions:
  api:
    handler: handler.main
    events:
      - http:
          path: /
          method: POST

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
